EG: SlideGraph Pipeline As Advance Example Usage
TissueImageAnalytics/tiatoolbox pull request #180
Opened 2021-10-28 16:53 UTC by vqdang

Finally something to bind all the parts in the toolbox together for a single purpose.

- [x] Framework conversion
- [x] Inference integrity check
- [x] Training integrity check
- [x] Add cell compositions
- [x] Explanation  
- [ ] ~~Performance Tests~~

There are several parts / considerations that may need to be split into / implemented by other PR during the making of this notebook to reduce its complexity

- Generating some specific train/valid/test split
- Drawing generic graph
- Drawing graph by a specific method
- Classifcal feature extraction
  - Cell compositions of patches
  - Nuclei morphology
- Extending some sklearn with `partial_fit` as fitting 1mllion ResNet50 vectors is impossible (OOM)
- Full training engine (may be far into the future)

Lastly, full pipeline as a notebook is bad for organizing code. Perhaps, we should maintain a subfolder called `pipeline` within `examples`, such as `examples/pipeline/slidehgraph` will contain `.py` code of slide graph (parts split/merge from notebook). Additionally, due to the complexity of making a pipeline, tests should also be written, however, notebooks won't facilitate that easily. These tests will focus solely on behavior tests i.e at least being able to replicate the original paper results.

2021-11-12 16:39 UTC, vqdang commented on examples/slide_graph.ipynb
> +{"cells":[{"cell_type":"markdown","source":[" # Preparation code"],"metadata":{}},{"cell_type":"markdown","source":[" ## Importing related libraries utilized throughout the notebook"],"metadata":{}},
<p>Sample comment</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/180/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-11-15 22:58 UTC, DavidBAEpstein requested changes
[sg_edited.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7542092/sg_edited.docx)
I suggest accepting or rejecting my suggested changes using the facilities of Word.
Subsequently one can copy and paste chunks of text into the notebook. Note that the conversion process ipynb -> docx does not deal correctly with code snippets in text cells or with python variable names in text cells. So some detailed manual work may be needed.

I have put some important remarks into comments. Please read them.

2021-11-30 16:13 UTC, shaneahmed commented on tiatoolbox/tools/scale.py
> +import numpy as np
licensing information missing at the top.

2021-11-30 16:14 UTC, shaneahmed commented on tiatoolbox/utils/visualization.py
> +    """
can we add example usage?

2021-12-01 20:58 UTC, DavidBAEpstein reviewed
Here are my comments of slide_graph.ipynb. Comments on the inference notebook will come later. I changed the format ipynb -> html -> docx, so that I could make suggestions in Track Mode. I attach the docx file. Please find my suggestions by using review mode in Word and clicking on "Next" for the next suggestion. Also please look at the comments in the comment boxes. If you are puzzled by any particular suggestion, I would be happy to explain my reasons.
[DE_TRK_slide_graph.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7637027/DE_TRK_slide_graph.docx)
Comments on slide_graph_inference.ipynb still to come..

2021-12-03 12:20 UTC, DavidBAEpstein requested changes
Small suggestions are easy to miss. Please use TRK next/previous Accept/Reject to find all my suggestions. I try to remove words or phrases that do not add information. In general, shorter sentences are easier to understand. Please check my suggestions to make sure they are correct.
[DE_TRK_slide_graph_inference.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7649516/DE_TRK_slide_graph_inference.docx)

2021-12-07 12:44 UTC, DavidBAEpstein reviewed
I went through examples/inference-pipelines/slide-graph.ipynb and made a few (very few) suggestions. I decided not to bother with Colab, as this has been checked by Dang and probably by the other reviewers. I will also look at the full pipeline version for grammar and meaning.
[2DE-TRK-slide-graph.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7668318/2DE-TRK-slide-graph.docx)
.

2021-12-08 20:35 UTC, DavidBAEpstein reviewed
Find suggested changes using Track Changes
[DE-TRK-full-pipeline-slide-graph.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7678780/DE-TRK-full-pipeline-slide-graph.docx)
.

2021-12-17 11:58 UTC, merged