EG: Example notebook for prediction of molecular pathways and key mutations
TissueImageAnalytics/tiatoolbox pull request #189
Opened 2021-11-03 11:46 UTC by simongraham

Added example notebook for mutation prediction. Included in this repo are some additional changes:

- functionality to overlay probability map
- Addition of IDaRS pretrained weights to the TIAToolbox server

2021-11-04 21:43 UTC, DavidBAEpstein requested changes
See ReviewNB. Please fix code so that it can be run in Colab. (Admittedly, I haven't tried to run it, but it seems to me that it wouldn't run.)
There needs to be some advice on to how to arrange for GPU use on Colab, possibly also on other platforms. I will carry on reviewing once the notebook runs on Colab (without GPU), and you can respond to comments about text cells at your leisure, for example waiting until I have gone through the whole notebook once.

2021-11-09 21:09 UTC, DavidBAEpstein requested changes
Although 8 files have been changed, I looked only at the 07 jupyter notebook.
I found two independent fatal errors. I have made comments in ReviewNB. The first error was obvious, so I just commented it out and tried running the notebook under Colab. The error message from the second fatal error is given in full in ReviewNB.

2021-11-12 11:28 UTC, shaneahmed commented on tiatoolbox/models/engine/patch_predictor.py
> +# The Original Code is Copyright (C) 2021, TIALab, University of Warwick
It should be `TIA Centre`

2021-11-23 17:10 UTC, DavidBAEpstein reviewed
The grammar is fine. In the last cell "We welcome you to ..."  is unusual, but OK. More usual would be "You are welcome to ....".
The notebook seems to be in better shape than when I last looked at it. But it still depends on Dang's personal file system, so it can't be merged yet. The notebook is not yet in a form where it can be run with GPU in Colab. I hope that it is the intention to fix that.

2021-11-23 18:04 UTC, DavidBAEpstein reviewed
I see nothing wrong with the grammar of the 08 notebook. The objections I had previously to merging remain, namely that 1) the merged version must avoid using Dang's private files, and 2) the notebook should be set up to run a GPU under Colab. The final text cell could be phrased in a more usual form as "You are welcome to ..." rather than "We welcome you to ..." but it's acceptable in the current form.

2021-11-28 10:00 UTC, DavidBAEpstein requested changes
I saved your notebook in HTML format (using jupyter notebook > File > Download As) and then used Track format (TRK) in MS Word to record suggested changes---there were not many of these. Please use TRK to find my suggested changes. The conversion process introduced a few errors. I should try using nbconvert.
[08_example_mutationprediction.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7613188/08_example_mutationprediction.docx)
s.

2021-11-29 09:57 UTC, shaneahmed commented on setup.py
> +    "pygeos",
this is being removed. Please make sure you update this after #202 is merged.

2021-12-10 13:11 UTC, DavidBAEpstein requested changes
[DE_TRK_01_idars.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7692908/DE_TRK_01_idars.docx)
please use "next" in Word > Review > Track changes
to find all the suggestions (of which there are very few).
Feel free to ignore suggestions that you don't agree with.

2021-12-17 10:02 UTC, simongraham commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-17 10:06 UTC, simongraham commented
<p>Sorted</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-17 11:07 UTC, simongraham commented
<p>Done</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2021-12-17 17:02 UTC, merged