DOC: Update docs with Docker instructions
TissueImageAnalytics/tiatoolbox pull request #286
Opened 2022-02-14 13:21 UTC by ghadjigeorghiou

2022-02-15 09:22 UTC, shaneahmed commented on docs/installation.rst
> +If you want to run TIA toolbox in an isolated environment, you can use our `Docker image <https://github.com/tissueimageanalytics/tiatoolbox-docker/pkgs/container/tiatoolbox>`_ . Furthermore, we host
```suggestion
If you would like to run TIA toolbox in an isolated environment, you can use our `Docker image <https://github.com/tissueimageanalytics/tiatoolbox-docker/pkgs/container/tiatoolbox>`_ . We host different Dockerfiles in our `tiatoolbox-docker <https://github.com/TissueImageAnalytics/tiatoolbox-docker>`_ github repository. Please report any issues related to docker image in the `tiatoolbox-docker <https://github.com/TissueImageAnalytics/tiatoolbox-docker>` repository. 
```

2022-02-15 09:23 UTC, shaneahmed commented on docs/installation.rst
> +Pull the image from the Github Container Registry
```suggestion
1. Pull the image from the Github Container Registry
```

2022-02-15 09:24 UTC, shaneahmed commented on docs/installation.rst
> +Use the image as a base image in a Dockerfile
```suggestion
2. Use the image as a base image in a Dockerfile
```

2022-02-15 09:24 UTC, shaneahmed commented on docs/installation.rst
> +Pull the image from the Github Container Registry
May be add a heading as you have for build the image locally

2022-02-15 09:25 UTC, shaneahmed commented on docs/installation.rst
> +
```suggestion

Use the pre-built docker image
^^^^^^^^^^^^^^^^^^^^
```

2022-02-15 09:26 UTC, shaneahmed requested changes
Please can you address the changes as mentioned.

2022-02-18 13:00 UTC, DavidBAEpstein requested changes
Change word order to standard English usage, as made explicit in this diff file
[installation_diff.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8097287/installation_diff.txt)
However, I didn't know how to typeset my raw version of installation.rst, so I can not be absolutely certain that the typesetting will be correct. 
.

2022-02-18 13:48 UTC, shaneahmed commented on docs/installation.rst
> +If you would like to run TIA toolbox in an isolated environment, you can use our `Docker image <https://github.com/tissueimageanalytics/tiatoolbox-docker/pkgs/container/tiatoolbox>`_ . We host differ
```suggestion
To run TIA toolbox in an isolated environment, use our `Docker image <https://github.com/tissueimageanalytics/tiatoolbox-docker/pkgs/container/tiatoolbox>`_ . We host different Dockerfiles in our github repository `tiatoolbox-docker <https://github.com/TissueImageAnalytics/tiatoolbox-docker>`_ github repository. Please report any issues related to docker image in the repository `tiatoolbox-docker <https://github.com/TissueImageAnalytics/tiatoolbox-docker>` repository. 
```

2022-02-18 13:50 UTC, shaneahmed commented
> Change word order to standard English usage, as made explicit in this diff file [installation_diff.txt](https://github.com/TissueImageAnalytics/tiatoolbox/files/8097287/installation_diff.txt) However, I didn't know how to typeset my raw version of installation.rst, so I can not be absolutely certain that the typesetting will be correct. .

Thanks David. I have added your suggestions above. @ghadjigeorghiou please address these. We can merge once @Srijay-lab  is happy.

2022-02-21 17:01 UTC, shaneahmed approved these changes

2022-02-22 09:29 UTC, merged