BUG: Add warning for VahadaneExtractor algorithm instability
TissueImageAnalytics/tiatoolbox pull request #871
Opened 2024-10-11 16:27 UTC by mostafajahanifar

This PR adds a warning to the VahadaneExtractor class to inform users about the algorithm's instability due to changes in the dictionary learning algorithm in scikit-learn versions > 0.23.0 (see issue #382). The docstrings are updated accordingly to reflect this warning. No other functionality is altered.

2024-10-18 13:55 UTC, shaneahmed commented on tiatoolbox/tools/stainextract.py
> +        logger.warning(
@mostafajahanifar Please can you add links to alternatives as discussed during the meeting?

2024-10-18 13:56 UTC, shaneahmed requested changes
Thanks @mostafajahanifar. Please can you add links to alternative repos users can use. Also, please can you add test using pytest capture caplog.text to verify the warning is caught?

2024-11-08 17:04 UTC, mostafajahanifar commented
> Thanks @mostafajahanifar. Please can you add links to alternative repos users can use. Also, please can you add test using pytest capture caplog.text to verify the warning is caught?

Thanks for the comments Shan. I have made your requested changes. Please feel free to review/merge.

2024-11-08 17:23 UTC, shaneahmed approved these changes
Thanks @mostafajahanifar

2024-11-08 17:25 UTC, merged